version: '2'
services:
  reportsample-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/reportSample/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=reportSample
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
